permivac/intranet/urls.py
from django.urls import include, path
from django.conf.urls import url
from django.urls import reverse
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^$', views.index, name='indexIntranet'),
    url(r'^noticies/',views.noticies, name='noticies'),
    url(r'^nova_noticia/',views.nova_noticia, name='nova_noticia'),
    url(r'^marcatge/',views.marcatge, name='marcatge'),
    path('accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

permivac/permivac/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from intranet import views
from tramitador import views as views_intranet

admin.site.site_header = "RRHH AjSVC Admin"
admin.site.site_title = "RRHH AjSVC Portal"
admin.site.index_title = "Benvingut al tramitador de RRHH AjSVC"
urlpatterns = [
    url(r'^$',views.redireccio),
    url(r'^tramitador/', include('tramitador.urls')),
    url(r'^intranet/', include('intranet.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$/accounts/login/',views_intranet.redireccio),
]

permivac/tramitador/urls.py
from django.urls import include, path
from django.conf.urls import url
from django.urls import reverse
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^nou_tramit/',views.nou_tramit, name='nou_tramit'),
    url(r'^historic/',views.historic, name='historic'),
    url(r'^calendari/',views.calendari, name='calendari'),
    url(r'^marcatges/',views.marcatges, name='marcatges'),
    path('tramit/<int:pk>/', views.tramit_detall, name='tramit_detall'),
    path('tramit_eliminar/<int:pk>/', views.tramit_eliminar, name='tramit_eliminar'),
    path('upload_document/', views.upload_document, name='pujar_document'),
    path('delete_document/', views.delete_document, name='eliminar_document'),
    path('assignades/',views.assignades, name="assignades"),
    path('validar/<int:pk>/<str:rol>', views.validar, name='validar'),
    path('denegar/<int:pk>/<str:rol>', views.denegar, name='denegar'),
    #url(r'^(?P<tramit_id>[0-9]+)/$',views.detall, name='detall'),
    #new line logins system jma
    path('accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

permivac/tramitador/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import datetime

# Create your models here.
from django.contrib.auth.models import AbstractUser

def year_choices():
    return [(r,r) for r in range(1984, datetime.date.today().year+2)]

def current_year():
    return datetime.date.today().year

class Area(models.Model):
    nom = models.CharField(max_length=100)
    def __str__(self):
        return self.nom

class Treballadors(AbstractUser):

    """tip_rols = (
        ('treb', 'Treballador'),
        ('resp', 'Responsable'),
        ('pol', 'Politic'),
    )
    tip_estats = (
        ('alta', 'Alta'),
        ('baixa','Baixa'),
    )
    creat_en = models.DateTimeField(auto_now_add=True)
    modificat_en = models.DateTimeField(auto_now=True)"""
    usuari = models.CharField(max_length=20)
    foto = models.FileField(upload_to='fotos', blank=True, null=True)
    """nom = models.CharField(max_length=20)
    cognoms = models.CharField(max_length=20)
    email = models.CharField(max_length=50)"""
    dni = models.CharField(max_length=20, null = True, blank=True)
    areas = models.ManyToManyField(Area)
    id_crosschex = models.IntegerField(max_length=4, null = True, blank=True)
    pass_crosschex =  models.IntegerField(max_length=4, null = True, blank=True)
    observacions = models.TextField(null = True, blank=True)
    """rol = models.CharField(max_length=20, choices = tip_rols, default = 'treb')
    estat = models.CharField(max_length=10, choices = tip_estats, default = 'alta')"""
    representant = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null = True)
    class Meta:
        ordering = ['first_name','last_name']

    def __str__(self):
        return self.username

class Document(models.Model):
    descripcio = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='%Y/%m/')
    pujat_en = models.DateTimeField(auto_now_add=True)
    pujat_per = models.ForeignKey(Treballadors, on_delete=models.CASCADE)

    def __str__(self):
        return self.descripcio

class Tramit(models.Model):
    validacio = (
        ('conforme','conforme'),
        ('inconforme','no conforme'),
        ('espera', 'en espera'),
    )
    tipologia = (
        ('vacances', 'Vacances'),
        ('perm_precep', 'Permisos preceptius'),
        ('perm_no_precep', 'Permisos no preceptius'),
        ('asum_p', 'Asumptes personals'),
        ('perm_indisposicio', 'Permis Indisposicio'),
        ('perm_altres', 'Altres permissos'),
    )
    treballador = models.ForeignKey(Treballadors, on_delete=models.CASCADE)
    document = models.ForeignKey(Document, on_delete=models.SET_NULL, null=True, blank=True)
    creat_en = models.DateTimeField(auto_now_add=True)
    modificat_en = models.DateTimeField(auto_now=True)
    data_sol = models.CharField(max_length=250, help_text = "Interval de dates amb guións '/', per dies no consecutios emprar ';' Exemple:2019-08-01-2019-08-20;2019-09-09")
    tipus = models.CharField(max_length=40, choices=tipologia, default='asum_p')
    finalitzat = models.BooleanField(default=False)

    """Validacio de RRHH"""
    valRRHH = models.CharField(max_length=20, choices=validacio, default='espera')

    """Validacio del responsable"""
    valResp =  models.CharField(max_length=20, choices=validacio, default='espera')

    """Validacio del Politic"""
    valPol = models.CharField(max_length=20, choices=validacio, default='espera')

    """En cas de voler explicar el motiu"""
    missatge_usuari = models.CharField(max_length=2000, null = True)
    missatge_responsable = models.CharField(max_length=2000, null = True, blank=True)

    """Millores per el admin site"""
    def was_published_recently(self):
        return self.creat_en >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'creat_en'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Publicat recentment?'

    def save(self, *args, **kwargs):
        if(self.valRRHH == "conforme" and self.valResp=="conforme" and self.valPol =="conforme"):
            self.finalitzat = True
        super(Tramit, self).save(*args, **kwargs)

    def __str__(self):
        return self.treballador.usuari

class Calendari(models.Model):
    any = models.IntegerField(('any'),choices=year_choices(), default=current_year())
    vacances = models.IntegerField(default=22, verbose_name="Vacances disponibles")
    vacances_dies = models.CharField(max_length=500, blank=True)
    perm_precep = models.IntegerField(default=0, verbose_name="Permissos preceptius fets:")
    perm_precep_dies = models.CharField(max_length=500, blank=True)
    perm_no_precep = models.IntegerField(default=0, verbose_name="Permissos no preceptius fets:")
    perm_no_precep_dies = models.CharField(max_length=500, blank=True)
    asum_p = models.IntegerField(default=6,verbose_name="Assumptes perosnals disponibles:")
    asum_p_dies = models.CharField(max_length=500, blank=True)
    perm_indisposicio = models.IntegerField(default=0, verbose_name="Permissos per indisposició fets:", blank=True)
    perm_indisposicio_dies = models.CharField(max_length=500, blank=True)
    perm_altres = models.IntegerField(default=0, verbose_name="Altres permissos", blank=True)
    perm_altres_dies = models.CharField(max_length=500, blank=True)

    treballador = models.ForeignKey(Treballadors, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.any)

permivac/tramitador/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Treballadors, Tramit, Document

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = Treballadors
        fields = ('username','password')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = Treballadors
        fields = ('username','first_name','last_name','dni','email','areas','observacions','foto')

class TramitSolForm(forms.ModelForm): #Classe per el formulari de nou tramit, sense acces als camps de validacio del Responsable i del politic.
    class Meta:
        model = Tramit
        fields = ('data_sol','tipus', 'missatge_usuari')
        widgets = {
            'data_sol': forms.HiddenInput(),
            'missatge_usuari':forms.Textarea(attrs={'rows':4, 'cols':150}),
            }
        labels = {
            'data_sol': ('Data/es que es sol·licita/en:'),
            'tipus': ('Tipus de permís:'),
            'missatge_usuari' : ('Missatge optatiu a destacar:'),
        }
        help_text = {
            'data_sol': ("Interval de dates amb guións '-', per dies no consecutios emprar ',' Exemple:01/01/2019 - 05/01/2019, 07/01/2019" ),
        }

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('document',)

permivac/tramitador/templates/tramits/assignades.html
{% extends 'tramits/base.html' %}

{% block content %}
<div class='flotant'>
  <form method="POST" id="enviarmsg">{% csrf_token %}
    <label for='missatge'>Missatge:</label>
    <textarea name='missatge' id='missatge' cols='50' rows='4'></textarea>
    <input type="hidden" value="" name="id">

    <button type="button" class="btn btn-default btn-sm" name="tancar">
      <span class="glyphicon glyphicon-remove"></span> Tancar
    </button>
    <button type='submit' value='Dessar' class="btn btn-default btn-sm">
      <span class="glyphicon glyphicon-ok"></span> Desar
    </button>
  </form>
</div>
  {% if tramits_pendents %}
  <h4>Tramits Pendents de finalitzar:</h4>
    <table class="TFtable sortable ordenable">
      <tr>
        <th>Tràmit</th><th>Tipus</th><th>Nom</th><th>Cognoms</th><th>Data sol·licitud</th><th>Finalitzat?</th><th>Accions</th><th>Document</th><th>Missatge</th><th>Validacio Responable</th><th>Validacio RRHH</th>
        <th>Validacio Politic</th>
      </tr>
      {% for tramit in tramits_pendents %}
      <tr>
        <td><a href="{% url 'tramit_detall' tramit.id %}">Veure tràmit num:{{tramit.id}}</a></td><td>{{tramit.tipus}}</td><td>{{tramit.treballador.first_name}}</td><td>{{tramit.treballador.last_name}}</td>
        <td>{{tramit.data_sol}}</td><td>{{tramit.finalitzat}}</td><td><a href="{% url 'tramit_eliminar' tramit.id %}" onclick="return confirm('Estas segur de vole eliminar el tràmit?')" class="glyphicon glyphicon-remove"></a></td>
        <td>
          {% if tramit.document %}

            <a href='/static/documents/upload/{{ tramit.document.document }}' class="glyphicon glyphicon-save-file"></a>
          {% else %}
            <small>Sense documents</small>
          {% endif %}
        </td>
        <td>
          <button type="button" value="{{tramit.id}}" class="btn btn-default btn-sm missatges_btn" name="missatges_btn">
            <span class="glyphicon glyphicon-pencil"> Editar</span>
          </button>
        </td>
        <td>
          {% if 'responsables' in rol %}
            <a href="{% url 'validar' tramit.id 'responsables' %}" class="glyphicon glyphicon-ok-sign" title="Validar el Tràmit" id="validar" data-tramit="{{tramit.id}}" data-rol="{{rol}}"></a>
            <a href="{% url 'denegar' tramit.id 'responsables' %}" class="glyphicon glyphicon-remove-sign" title="Denegar el Tràmit" id="denegar" onclick="return confirm('Estas segur de voler denegar el tràmit?')" data-tramit="{{tramit.id}}" data-rol="{{rol}}"></a>
          {% endif %}
          {{tramit.valResp}}
        </td>
        <td>
          {% if 'RRHH' in rol %}
            <a href="{% url 'validar' tramit.id 'RRHH' %}" class="glyphicon glyphicon-ok-sign" title="Validar el Tràmit" id="validar" data-tramit="{{tramit.id}}" data-rol="{{rol}}"></a>
            <a href="{% url 'denegar' tramit.id 'RRHH' %}" class="glyphicon glyphicon-remove-sign" title="Denegar el Tràmit" id="denegar" onclick="return confirm('Estas segur de voler denegar el tràmit?')" data-tramit="{{tramit.id}}" data-rol="{{rol}}"></a>
          {% endif %}
            {{tramit.valRRHH}}
        </td>
        <td>
          {% if 'politics' in rol %}
            <a href="{% url 'validar' tramit.id 'politics' %}" class="glyphicon glyphicon-ok-sign" title="Validar el Tràmit" id="validar" data-tramit="{{tramit.id}}" data-rol="{{rol}}"></a>
            <a href="{% url 'denegar' tramit.id 'politics' %}" class="glyphicon glyphicon-remove-sign" title="Denegar el Tràmit" id="denegar" onclick="return confirm('Estas segur de voler denegar el tràmit?')" data-tramit="{{tramit.id}}"data-rol="{{rol}}"></a>
          {% endif %}
            {{tramit.valPol}}
        </td>

      </tr>
      {% endfor %}
    </table>

  {% endif %}

  {% if tramits_pendents_RRHH %}
    <h4>Tramits Pendents com a RRHH:</h4>
    <table class="TFtable sortable ordenable">
      <tr>
        <th>Tràmit</th><th>Tipus</th><th>Nom</th><th>Cognoms</th><th>Data Sol·licitud</th><th>Finalitzat?</th><th>Accions</th><th>Document</th><th>Missatge</th><th>Validacio Responable</th><th>Validacio RRHH</th>
        <th>Validacio Politic</th>
      </tr>
      {% for tramit in tramits_pendents_RRHH %}
      <tr>
        <td><a href="{% url 'tramit_detall' tramit.id %}">Veure tràmit num:{{tramit.id}}</a></td><td>{{tramit.tipus}}</td><td>{{tramit.treballador.first_name}}</td><td>{{tramit.treballador.last_name}}</td>
        <td>{{tramit.data_sol}}</td><td>{{tramit.finalitzat}}</td><td><a href="{% url 'tramit_eliminar' tramit.id %}" onclick="return confirm('Estas segur de vole eliminar el tràmit?')" class="glyphicon glyphicon-remove"></a></td>
        <td>
          {% if tramit.document %}

            <a href='/static/documents/upload/{{ tramit.document.document }}' class="glyphicon glyphicon-save-file"></a>
          {% else %}
            <small>Sense documents</small>
          {% endif %}
        </td>
        <td>
          <button type="button" value="{{tramit.id}}" class="btn btn-default btn-sm missatges_btn" name="missatges_btn">
            <span class="glyphicon glyphicon-pencil"> Editar</span>
          </button>
        </td>
        <td>
          {% if 'responsables' in rol %}
            <a href="{% url 'validar' tramit.id 'responsables' %}" class="glyphicon glyphicon-ok-sign" title="Validar el Tràmit" id="validar" data-tramit="{{tramit.id}}" data-rol="responsables"></a>
            <a href="{% url 'denegar' tramit.id 'responsables' %}" class="glyphicon glyphicon-remove-sign" title="Denegar el Tràmit" id="denegar" data-tramit="{{tramit.id}}" data-rol="responsables" onclick="return confirm('Estas segur de voler denegar el tràmit?')"></a>
          {% endif %}
          {{tramit.valResp}}
        </td>
        <td>
          {% if 'RRHH' in rol %}
            <a href="{% url 'validar' tramit.id 'RRHH' %}" class="glyphicon glyphicon-ok-sign" title="Validar el Tràmit" id="validar" data-tramit="{{tramit.id}}" data-rol="RRHH"></a>
            <a href="{% url 'denegar' tramit.id 'RRHH' %}" class="glyphicon glyphicon-remove-sign" title="Denegar el Tràmit" id="denegar" data-tramit="{{tramit.id}}" data-rol="RRHH"  onclick="return confirm('Estas segur de voler denegar el tràmit?')"></a>
          {% endif %}
            {{tramit.valRRHH}}
        </td>
        <td>
          {% if 'politics' in rol %}
            <a href="{% url 'validar' tramit.id 'politics' %}" class="glyphicon glyphicon-ok-sign" title="Validar el Tràmit" id="validar" data-tramit="{{tramit.id}}" data-rol="politics"></a>
            <a href="{% url 'denegar' tramit.id 'politics' %}" class="glyphicon glyphicon-remove-sign" title="Denegar el Tràmit" id="denegar" data-tramit="{{tramit.id}}"data-rol="politics"></a>
          {% endif %}
            {{tramit.valPol}}
        </td>

      </tr>
      {% endfor %}
    </table>
    {% else %}
      <p>No hi han tramits pendentsde de tramitar...</p>
    {% endif %}
{% endblock %}
{% block javascript %}
  <script>
    $(document).ready(function(){
      $("button[name=missatges_btn]").click(function(e){
        console.log("Valor = "+$(this).val());
        $(this).prepend($("#divForm"));
        $('.flotant').css('display','flex');
        $("input[name='id']").val($(this).val());
        console.log($("input[name='id']").val());


      });
      $("button[name=tancar]").click(function(e){
        $('.flotant').css('display','none');
      });
      $('.flotant').submit(function(e){
        $('.flotant').css('display','none');
      });
    });
  </script>
{% endblock %}

permivac/tramitador/templates/tramits/base.html
<!DOCTYPE html>
{% load static %}
{% load group %}

<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tramitador RRHH AjSVC</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'tramits/style.css' %}">
    <link rel="stylesheet" href="{% static 'tramits/bootstrap-year-calendar.css' %}">

  </head>
  <body>
    <div id="heading">
      {% block heading %}
        {% if user.is_authenticated %}
          Bevingut sr/a {{ user.first_name }} {{ user.last_name }}
        {% endif %}
      {% endblock %}
    </div>
    {% if not user.is_authenticated %}
      <div id="senseacces" class="col-md 12 well">
        <div><h4>Acces a l'aplicació Permisos i Vacances AjSVC</h4></div>
        <div><p>Encara no t'has autentificat:</p>
          <a href="{% url 'login' %}"><button type="button" class="btn btn-primary">Entrar</button></a>
        </div>
      </div>
    {% endif %}
    {% if user.is_authenticated %}

      <div id="main_block">
        <div id="options_block">
          <ul class="menu_options">
            <li><a href="{% url 'index' %}" class="active">Inici</a></li>
            <li><a href="{% url 'indexIntranet' %}"class ="glyphicon glyphicon-th">Intranet</a></li>
            <li><a href="{% url 'nou_tramit' %}"class ="glyphicon glyphicon-plus">Solicitud</a></li>
            {% if request.user|has_group:"RRHH;responsables;politics" %}
              <li><a href="{% url 'assignades' %}">Assignades</a></li>
            {% endif %}

            <li><a href="{% url 'historic' %}">Historic</a></li>
            <li><a target="_blank" href="{% static 'documentacio/manual.pdf' %}">Informacio sobre el Tramit</a></li>
            <li><a target="_blank" href="{% url 'calendari' %}">Calendari</a></li>
            <li><a target="_blank" href="{% url 'marcatges' %}">Marcatges</a></li>
            <li class="menu_options_dreta"><a href="{% url 'logout' %}">Sortir</a></li>
            <li class="menu_options_dreta"><a href="/permivac/tramitador/accounts/password_change/">Canviar la contrasenya</a></li>

          </ul>
        </div>
        {% block content %}
        {% endblock %}
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="{% static 'js/jquery-3.4.1.js' %}"></script>
                <!--<script src="https://code.jquery.com/jquery-1.12.4.js"></script>-->
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        <script src="{% static 'js/bootstrap-year-calendar.js' %}"></script>
        <script src="{% static 'js/bootstrap-year-calendar.es.js' %}"></script>
        <script src="{% static 'js/sorttable.js' %}"></script>

      </div>
      {% block javascript %}

      {% endblock %}

    {% endif %}

  </body>
</html>

permivac/tramitador/templates/tramits/tramit_edit.html
{% extends 'tramits/base.html'%}
{% load crispy_forms_tags %}
{% block content %}

<div id="main_table">

  <h4>Nova Sol·licitud de Permissos i Vacances</h4>
  <div id="calculadora">
    <h4>Calcula les dades de sol·icitud</h4>
    <div class="seccio">
      Del:<input type="text" name="display1" id="display1"/>Al:
      <input type="text" name="display2" id="display2" />
    </div>
    <div id="seccio">
      <label for="opcio">Opcions:</label>
      <div class="radio">
        <label><input type="radio" name="opcio" value="interval" checked>Interval de dates</label>
      </div>
      <div class="radio">
        <label><input type="radio" name="opcio" value="single">Dies independents</label>
      </div>
    </div>
    <div id="seccio">
      <button type="button" class="btn" id="add_btn">Afegir</button>
      <button type="button" class="btn btn-danger" id="reset_btn">Reiniciar</button>
      <input type="text" name="dates_shadow" id="dates_shadow" disabled="disabled" size="100" value="">
    </div>
  </div>
  <form method="POST" class="post-form">
    {% csrf_token %}
    {% for field in form.visible_fields %}
      <div class="form-group">
        {{field.label_tag}}
        {{field}}
        {% if field.help_text %}
          <small class="form-text text-muted">{{field.help_text}}</small>
        {% endif %}
      </div>
      {% endfor %}
      {% for hidden_field in form.hidden_fields %}
        {{ hidden_field.errors }}
        {{ hidden_field }}
      {% endfor %}

    <input type="hidden" name="next" value="{{ next }}">
    <input class="btn btn-success" type="submit" value="Desar">
  </form>
</div>
{% endblock %}
{% block javascript %}
  <script>
    $(document).ready(function(){
      $("#display1").datepicker({ dateFormat: 'yy-mm-dd', beforeShowDay:setHoliDays });
      $("#display2").datepicker({ dateFormat: 'yy-mm-dd', beforeShowDay:setHoliDays });
      /*$("#id_data_sol").prop('disabled', true);*/
      $.datepicker.regional['es'] = {
      closeText: 'Tancar',
      prevText: '<Ant',
      nextText: 'Sig>',
      currentText: 'Avui',
      monthNames: ['Gener', 'Febrer', 'Març', 'Abril', 'Maig', 'Juny', 'Juliol', 'Agost', 'Septembre', 'Octubre', 'Novembre', 'Decembre'],
      monthNamesShort: ['Gen', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dec'],
      dayNames: ['Diumenge', 'Dilluns', 'Dimarts', 'Dimecres', 'Dijous', 'Divendres', 'Dissabte'],
      dayNamesShort: ['Diu', 'Dill', 'Dima', 'Dime', 'Dijo', 'Dive', 'Disb'],
      dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sá'],
      weekHeader: 'Sm',
      dateFormat: 'yy-mm-dd',
      firstDay: 1,
      isRTL: false,
      showMonthAfterYear: false,
      yearSuffix: ''
  };
  $.datepicker.setDefaults($.datepicker.regional['es']);

      $('input[type=radio][name=opcio]').change(function(){
        if(this.value=="interval"){
          $("#display1").prop("disabled", false);
          $("#display2").prop("disabled", false);
          opcio = "interval";
        }else if(this.value == "single"){
          $("#display2").val(null);
          $("#display2").prop("disabled", true);
        }

      });

      $("#add_btn").click(function(e){

        if( $("#display1").val().length === 0 ){
          alert("Has de introduir minim una data");
        }else if( ($('input[type=radio][name=opcio]:checked').val()=="single") ){
          var valor = $("#id_data_sol").val();
          valor = valor + $("#display1").val();
          $("#id_data_sol").val(valor+";");
          $("#dates_shadow").val(valor+";");
        }else if( ($('input[type=radio][name=opcio]:checked').val()=="interval") ){
          var valor = $("#id_data_sol").val();
          valor = valor + $("#display1").val() + "/" + $("#display2").val();
          $("#id_data_sol").val(valor+";");
          $("#dates_shadow").val(valor+";");
        }else{

        }
      });
      $("#reset_btn").click(function(e){
        $("#display1").val(null);
        $("#display2").val(null);
        $("#id_data_sol").val(null);
        $("#dates_shadow").val(null);
      });

    function setHoliDays(date) {
        for (i = 0; i < holiDays.length; i++) {
          if (date.getFullYear() == holiDays[i][0]
             && date.getMonth() == holiDays[i][1] - 1
               && date.getDate() == holiDays[i][2]) {
             return [true, 'holiday', holiDays[i][3]];
          }
        }
       return [true, ''];
    }
    /*Codi Per editar els dies festius del datepicker*/
    var holiDays =[[2019,01,01,'Any nou'],[2019,01,22,'Festiu'],[2019,04,19,'Festiu'],
    [2019,04,22,'Festiu'],[2019,05,01,'Festiu'],[2019,06,24,'Festiu'],[2019,07,15,'Festiu'],
    [2019,08,15,'Festiu'],[2019,09,11,'Festiu'],[2019,10,12,'Festiu'],[2019,11,01,'Festiu'],
    [2019,12,06,'Festiu'],[2019,12,25,'Festiu'],[2019,12,26,'Festiu'],
    [2020,01,01,'Any nou'],[2020,01,06,'Festiu'],[2020,01,22,'Festiu'],[2020,04,10,'Festiu'],
    [2020,04,13,'Festiu'],[2020,05,01,'Festiu'],[2020,06,24,'Festiu'],[2020,07,13,'Festiu'],
    [2020,08,15,'Festiu'],[2020,09,11,'Festiu'],[2020,10,12,'Festiu'],[2020,12,08,'Festiu'],
    [2020,12,25,'Festiu'],[2020,12,26,'Festiu']];
    });
  </script>
{% endblock %}